from . import views

data_dict_1 = {
    'Name': 'Kavya',
    'RegNo': '22AIA53',
    'Department': 'AI&DS',
    'Grade': 'A',
    'course_id_1': 'GE3252',
    'course_id_2': 'MA3151',
    'course_id_3': 'MA3251',
    'course_id_4': 'PH3151',
    'course_id_5': 'CY3151',
    'course_id_6': 'GE3151',
    'course_name_1': 'TAMIL AND TECHNOLOGY',
    'course_name_2': 'MATRICES AND CALCULUS',
    'course_name_3': 'PROFESSIONAL ENGLISH I',
    'course_name_4': 'ENGINEERING PHYSICS',
    'course_name_5': 'ENGINEERING CHEMISTRY',
    'course_name_6': 'PSPP',
    'course_grade_1': 'A',
    'course_grade_2': 'A',
    'course_grade_3': 'A',
    'course_grade_4': 'A',
    'course_grade_5': 'A',
    'course_grade_6': 'A',
}

data_dict_2 = {
    'Name': 'Amala',
    'RegNo': '22AIA01',
    'Department': 'AI&DS',
    'Grade': 'A+',
    'course_id_1': 'GE3252',
    'course_id_2': 'MA3151',
    'course_id_3': 'MA3251',
    'course_id_4': 'PH3151',
    'course_id_5': 'CY3151',
    'course_id_6': 'GE3151',
    'course_name_1': 'TAMIL AND TECHNOLOGY',
    'course_name_2': 'MATRICES AND CALCULUS',
    'course_name_3': 'PROFESSIONAL ENGLISH I',
    'course_name_4': 'ENGINEERING PHYSICS',
    'course_name_5': 'ENGINEERING CHEMISTRY',
    'course_name_6': 'PSPP',
    'course_grade_1': 'A',
    'course_grade_2': 'A+',
    'course_grade_3': 'O',
    'course_grade_4': 'A+',
    'course_grade_5': 'A',
    'course_grade_6': 'A',
}

data_dict_3 = {
    'Name': 'Sakthi',
    'RegNo': '22AIA78',
    'Department': 'AI&DS',
    'Grade': 'O',
    'course_id_1': 'GE3252',
    'course_id_2': 'MA3151',
    'course_id_3': 'MA3251',
    'course_id_4': 'PH3151',
    'course_id_5': 'CY3151',
    'course_id_6': 'GE3151',
    'course_name_1': 'TAMIL AND TECHNOLOGY',
    'course_name_2': 'MATRICES AND CALCULUS',
    'course_name_3': 'PROFESSIONAL ENGLISH I',
    'course_name_4': 'ENGINEERING PHYSICS',
    'course_name_5': 'ENGINEERING CHEMISTRY',
    'course_name_6': 'PSPP',
    'course_grade_1': 'O',
    'course_grade_2': 'A+',
    'course_grade_3': 'O',
    'course_grade_4': 'A+',
    'course_grade_5': 'O',
    'course_grade_6': 'O',
}




data_dict_4= {
    'Name': 'Aishwarya',
    'RegNo': '22AIA06',
    'Department': 'AI&DS',
    'Grade': 'A',
    'course_id_1': 'GE3252',
    'course_id_2': 'MA3151',
    'course_id_3': 'MA3251',
    'course_id_4': 'PH3151',
    'course_id_5': 'CY3151',
    'course_id_6': 'GE3151',
    'course_name_1': 'TAMIL AND TECHNOLOGY',
    'course_name_2': 'MATRICES AND CALCULUS',
    'course_name_3': 'PROFESSIONAL ENGLISH I',
    'course_name_4': 'ENGINEERING PHYSICS',
    'course_name_5': 'ENGINEERING CHEMISTRY',
    'course_name_6': 'PSPP',
    'course_grade_1': 'A',
    'course_grade_2': 'A+',
    'course_grade_3': 'A',
    'course_grade_4': 'A+',
    'course_grade_5': 'A',
    'course_grade_6': 'A',
}


data_dict_5= {
    'Name': 'Joshika',
    'RegNo': '22AIA50',
    'Department': 'AI&DS',
    'Grade': 'A+',
    'course_id_1': 'GE3252',
    'course_id_2': 'MA3151',
    'course_id_3': 'MA3251',
    'course_id_4': 'PH3151',
    'course_id_5': 'CY3151',
    'course_id_6': 'GE3151',
    'course_name_1': 'TAMIL AND TECHNOLOGY',
    'course_name_2': 'MATRICES AND CALCULUS',
    'course_name_3': 'PROFESSIONAL ENGLISH I',
    'course_name_4': 'ENGINEERING PHYSICS',
    'course_name_5': 'ENGINEERING CHEMISTRY',
    'course_name_6': 'PSPP',
    'course_grade_1': 'A+',
    'course_grade_2': 'A+',
    'course_grade_3': 'A',
    'course_grade_4': 'A+',
    'course_grade_5': 'A+',
    'course_grade_6': 'A',
}